feat: allow oidc request configuration
5-stones/nest-oidc pull request #4
Opened 2023-04-19 09:50 UTC by BorisTB

We need to use custom certificates and settings to connect to our server and rn it's not possible without hacks

2023-04-20 15:02 UTC, jspizziri requested changes
@BorisTB ,

Thanks for the PR! All in all it looks good but I had two comments.

2023-04-20 15:02 UTC, jspizziri commented on src/services/auth.service.ts
> +        .get(`${this.oidcAuthority}/.well-known/openid-configuration`, this.oidcConfigRequestOptions)
Maybe I'm missing it, but I'm not seeing a default for the `oidcConfigRequestOptions` if it's not configured. Is it just defaulting to `undefined`?

2023-04-20 15:02 UTC, jspizziri commented on src/services/auth.service.ts
> +      throw new BadRequestException("There was an error when attempting to fetch openid-configuration\n" + err, { cause: err });
I'm not sure about this change. Is there a specific rationale for it?

2023-04-20 16:57 UTC, Ken-Michalak commented on src/services/auth.service.ts
> +      throw new BadRequestException("There was an error when attempting to fetch openid-configuration\n" + err, { cause: err });
It seems like we should log the error, but it probably shouldn't be in the exception message or the HTTP response.

It's not really a "BadRequest" either, since it's not anything wrong with what was in the request to the Nest app itself. It's probably more of an internal server error.

2023-04-25 11:58 UTC, BorisTB commented on src/services/auth.service.ts
> +        .get(`${this.oidcAuthority}/.well-known/openid-configuration`, this.oidcConfigRequestOptions)
Yes, default it undefined

2023-04-25 12:00 UTC, BorisTB commented on src/services/auth.service.ts
> +      throw new BadRequestException("There was an error when attempting to fetch openid-configuration\n" + err, { cause: err });
It's small fix to actually show some error in console (took me while to find out this library wasn't working for me because of missing certificate)

2023-04-25 12:07 UTC, jspizziri commented on src/services/auth.service.ts
> +      throw new BadRequestException("There was an error when attempting to fetch openid-configuration\n" + err, { cause: err });
@BorisTB I'd prefer to use the nestjs logger and simply call `this.logger.error(err)` or something similar rather than appending it to the Exception.

2023-07-26 14:21 UTC, jspizziri commented
I'm closing this due to lack of a response.

2023-07-26 14:21 UTC, closed without merging